version: '3.9'

networks:
  user-net:
    name: "user-net"

  rabbit-net:
    name: "rabbit-net"

  sql-net:
    name: "sql-net"
    external: false 

  web-net:
    name: "web-net"


volumes:
  db-data:

services:

  user.data:
    image: redis
    container_name: user.data
    networks:
      - user-net
   
  sql.data:
    build:
      context: .
      dockerfile: ./database.Dockerfile
    container_name: sql.data
    networks:
      - sql-net
    volumes:
      - ./volume-data:/var/opt/mssql/data
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
    networks:
      - rabbit-net
    # surveillance
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      # intervalles 
      interval: 10s
      # test ne répond pas 
      timeout: 5s
      # 3 tentatives supplémentaires 
      retries: 3
 
  applicants.api:
    build:
      context: .
      dockerfile: ./applicants.Dockerfile
    container_name: applicants.api
    # chaîne de connexion à une base de données.
    # le nom d'hôte du service RabbitMQ
    environment:
      - ConnectionString=Server=sql.data;User=sa;Password=Pass@word;Database=dotnetgigs.applicants;
      - HostRabbitmq=rabbitmq
    networks:
      - user-net
      - rabbit-net
      - sql-net
      - web-net
    depends_on:
      sql.data:
        # être en cours d'exécution 
        condition: service_started
        # Si "sql.data" fail
        restart: true
      # rabbitmq" doit être sain
      rabbitmq:
        condition: service_healthy
      user.data:
        condition: service_started
    restart: on-failure:5
  
  service-api-identity:
    build:
      context: .
      dockerfile: ./identity.Dockerfile
    container_name: identity.api
    #  l'adresse IP et le port de l'hôte Redis 
    environment:
      - RedisHost=user.data:6379
      - HostRabbitmq=rabbitmq
    networks:
      - user-net
      - rabbit-net
      - sql-net
      - web-net
      
    depends_on:
      sql.data:
        condition: service_started
        restart: true
      rabbitmq:
        condition: service_healthy
      user.data:
        condition: service_started
    restart: on-failure:5
  
  service-api-jobs:
    build:
      context: .
      dockerfile: ./jobs.Dockerfile
    container_name: jobs.api
    environment:
      - ConnectionString=Server=sql.data;User=sa;Password=Pass@word;Database=dotnetgigs.jobs;
      - HostRabbitmq=rabbitmq
    networks:
      - user-net
      - rabbit-net
      - sql-net
      - web-net

    depends_on:
      sql.data:
        condition: service_started
        restart: true
      rabbitmq:
        condition: service_healthy
      user.data:
        condition: service_started      
    restart: on-failure:5

  web:
      build:
        context: .
        dockerfile: ./web.Dockerfile
      container_name: web

      # l'URL de l'API 
      environment:
        - ApiSettings__IdentityApiUrl=http://service-api-identity
        - ApiSettings__JobsApiUrl=http://service-api-jobs
      ports:
        - "80:80"
      networks:
        - web-net
      depends_on:
        - applicants.api
        - service-api-identity
        - service-api-jobs
     
